### ISSUE TITLE
Missing toleration for master nodes in install documentation 

### ISSUE THREAD

**Issue by siwyroot** [openshift/ocs-operator#1180]
Hello,

Compliance Operator cannot run on OpenShift Container Storage as it's missing toleration for master nodes. I think  install docs need to be updated to include that or operator should include this by default.At this moment attaching PVC to master node fails with following error:

MountVolume.MountDevice failed for volume "pvc-04cce714-b99e-439f-b593-de260050e5b9" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name openshift-storage.cephfs.csi.ceph.com not found in the list of registered CSI drivers

Issue opened for compliance operator:
https://github.com/openshift/compliance-operator/issues/642

Could someone guide me how I can modify already deployed OCS cluster to include that tolleration?

**Comment by jarrpa** [comment]
Tolerations can be added using the `Spec.Placements` field, which is a Rook struct and can be looked up there. This is not yet a supported feature, so there is no official documentation nor any examples.

**Comment by james-cccc** [comment]
Would the following example of adding a master toleration in the rook-ceph-operator-config configmap be supported?  e.g.

```
apiVersion: v1
data:
  CSI_PLUGIN_TOLERATIONS: |
    - effect: NoSchedule
      key: nodetype
      operator: Equal
      value: master
    - effect: NoSchedule
      key: node.ocs.openshift.io/storage
      operator: Exists
kind: ConfigMap
```
**Ref:**
https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.6/html-single/managing_and_allocating_storage_resources/index#managing-container-storage-interface-component-placements_rhocs
