### ISSUE TITLE
Question: Why is hostNetwork configuration listed twice in StorageCluster CRD?

### ISSUE THREAD

**Issue by rcampos2029** [openshift/ocs-operator#1394]
The hostNetwork field is specified in two places on the StorageCluster CRD:
```
spec:
  hostNetwork: <bool>
  ...
  network:
    hostNetwork: <bool>
```

From testing we've found that the field directly within `spec:` achieves the desired result, while the field nested within the `network:` field does not. 

What is the purpose of the second `hostNetwork` field?

https://github.com/red-hat-storage/ocs-operator/blob/ac63e784864348f5ba4b6f42f51cf42997c197c3/config/crd/bases/ocs.openshift.io_storageclusters.yaml#L737
