### ISSUE TITLE
[ROKS] Port 9091 has to be made configurable in OCS

### ISSUE THREAD

**Issue by akgunjal** [openshift/ocs-operator#451]
OCS has hard-coded to use port 9091 today which clashes with Calico in RedHat OpenShift kubernetes service (ROKS). This needs to be made configurable so the OCS installation can take ports open in ROKS.

**Comment by travisn** [comment]
The port will be configurable in OCS 4.5 through a ConfigMap. The setting will need to be modified in the ConfgMap either by OCS or some higher level component than Rook that has the context about which port should be used. This is about ready for merge into Rook as seen in this PR: https://github.com/rook/rook/pull/5032

**Comment by akgunjal** [comment]
@umangachapagain : Why is this issue closed? OCS 4.5 is not yet released I guess. So it can be closed once its released and then with insttructions of how to use it.

**Comment by umangachapagain** [comment]
The fix is merged (as seen in the linked Pull Request) and we don't do Github Releases.
So this issue is closed.
For OCS 4.5 release, relevant issues are tracked in Bugzilla.

Here's what you need to create for using this feature:
```
# Use this ConfigMap to override operator configurations
# Precedence will be given to this config in case Env Var also exists for the same
#
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-ceph-operator-config
  # should be in the namespace of the operator
  namespace: openshift-storage
data:
  # Configure CSI Ceph FS grpc and liveness metrics port
  # CSI_CEPHFS_GRPC_METRICS_PORT: "9091"
  # CSI_CEPHFS_LIVENESS_METRICS_PORT: "9081"
  # Configure CSI RBD grpc and liveness metrics port
  # CSI_RBD_GRPC_METRICS_PORT: "9090"
  # CSI_RBD_LIVENESS_METRICS_PORT: "9080"
```
