### ISSUE TITLE
[ROKS] csi-cephfsplugin and csi-rbdplugin needs to change kubelet path

### ISSUE THREAD

**Issue by akgunjal** [openshift/ocs-operator#454]
The daemon sets csi-cephfsplugin and csi-rbdplugin need to use the path `/var/data/kubelet` as the kubelet path is different in ROKS. Ideally its better to find the kubelet path dynamically if possible.

**Comment by travisn** [comment]
The kubelet path for the CSI drivers will be configurable in OCS 4.5 through a ConfigMap. The setting will need to be modified in the ConfgMap either by OCS or some higher level component than Rook that has the context about which path should be specified. This is about ready for merge into Rook as seen in this PR: https://github.com/rook/rook/pull/5032

**Comment by mulbc** [comment]
As far as I can see rook/rook#5032 has been merged and consists of commit https://github.com/rook/rook/commit/0e932c15eb476ad4343552aee47bad00cd005245 which has been released with v1.3.0.

As far as I see, the OCS 4.5 release tag currently still points to an older Rook version:
https://github.com/openshift/ocs-operator/blob/6a3c3a2956de31e1addc20c382ead7e73d5372ed/deploy/olm-catalog/ocs-operator/4.5.0/ocs-operator.v4.5.0.clusterserviceversion.yaml#L1196

Is this correct or am I missing something?

**Comment by jarrpa** [comment]
That's just on GitHub, and we make no guarantees that they are strictly up to date not reflective of the full downstream product. We will have it for the first downstream OCS 4.5 builds.

**Comment by akgunjal** [comment]
@umangachapagain : Why is this issue closed? OCS 4.5 is not yet released I guess. So it can be closed once its released and then with insttructions of how to use it.

**Comment by umangachapagain** [comment]
The fix is merged (as seen in the linked Pull Request) and we don't do Github Releases.
So this issue is closed.
For OCS 4.5 release, relevant issues are tracked in Bugzilla.

Here's what you need to create for using this feature:
```
# Use this ConfigMap to override operator configurations
# Precedence will be given to this config in case Env Var also exists for the same
#
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-ceph-operator-config
  # should be in the namespace of the operator
  namespace: openshift-storage
data:
  # kubelet directory path, if kubelet configured to use other than /var/lib/kubelet path.
  # ROOK_CSI_KUBELET_DIR_PATH: "/var/lib/kubelet"
```
