### ISSUE TITLE
StorageCluster: Unbalaced distribution of OSDs by Topology spread on cluster with local PVs

### ISSUE THREAD

**Issue by kesavanvt** [openshift/ocs-operator#879]
the OSD pod distribution is not even for cluster with multiple nodes within a failure domain for local PVs

Steps to reproduce

1. Create a 9 node OCP cluster based on 3 AZs (east-us 1a,1b,1c) . 3 nodes per AZ
2. Attach 2 disk volumes for each node and create local PVs using LSO
3. Create initial OCS cluster selecting the storageClass created on the above step
4. Expand the storage twice

Actual result : within an AZ, single node had two OSDs, leaving one node to be unused.

Expected result : The OSDs should be equally distributed across each node within an AZ. (each node with 1 OSD)

**Comment by kesavanvt** [comment]
Currently, the placement for prepare pod is zone/rack based on the OCS calculation and its not distributed equally within a failure domain . The PVs created by prepare Jobs will contain further restrictions on where the PV can be mounted. For dynamic provisioning, OSD distribution is maintained as the PVs restriction is the failure domain of prepare job zone/rack. However for local PVs , the PVs restriction is to the host, so OSD placement is dependent on the placement of prepare pod. Thus multiple topology spread needs to be set for prepare pods. Top level would be for zone/rack , the bottom level would be for host. In case of flexible scaling it would be set to host without multiple TSC.


 ```
 topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: failure-domain.beta.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchExpressions:
          - key: app
            operator: In
            values:
              - rook-ceph-osd-prepare
              - rook-ceph-osd
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchExpressions:
          - key: app
            operator: In
            values:
              - rook-ceph-osd-prepare
              - rook-ceph-osd
```
