### ISSUE TITLE
OCS 4.5 on ocp 4.6. Instanciate StorageCluster from CLI not working

### ISSUE THREAD

**Issue by Sispheor** [openshift/ocs-operator#917]
Hi,

I'm trying to deploy OCS via Ansible. The last step consist into deploying the StorageCluster  object.
This last appears but nothing get deployed. If I create the StorageCluster  from the UI it's ok.

```yaml
- name: Create an OCS Cluster Service using dynamic storage devices
  k8s:
    kubeconfig: "{{ ocp_ignition_file_path }}/auth/kubeconfig"
    state: present
    definition:
      kind: StorageCluster
      apiVersion: ocs.openshift.io/v1
      metadata:
        name: ocs-storagecluster
        namespace: openshift-storage
      spec:
        externalStorage: {}
        storageDeviceSets:
          - config: {}
            count: 1
            dataPVCTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: "{{ ocp_ocs.storage_size }}"
                storageClassName: thin
                volumeMode: Block
              status: {}
            name: ocs-deviceset-thin
            placement: {}
            portable: true
            replica: 3
            resources: {}
        version: "{{ ocp_ocs.ocs_version }}"
```

Any idea of what I doing wrong? Thanks.
