### ISSUE TITLE
Question: StorageCluster deployment with only VMDK local volume (VMware)

### ISSUE THREAD

**Issue by Sispheor** [openshift/ocs-operator#951]
Hi,

I'm trying to deploy a StorageCluster based on VMDK local storage.
I don't find any doc or example about this kind of config.

Can I declare only a `monPVCTemplate` object without `storageDeviceSets`? Is 50GB per VMDK enough for testing? 

Here is my Ansible code to deploy my stack:
```yaml
- name: Create local volume
  k8s:
    kubeconfig: "{{ ocp_ignition_file_path }}/auth/kubeconfig"
    state: present
    definition:
      apiVersion: local.storage.openshift.io/v1
      kind: LocalVolume
      metadata:
        name: local-file
        namespace: openshift-local-storage
        labels:
          app: ocs-storagecluster
      spec:
        nodeSelector:
          nodeSelectorTerms:
          - matchExpressions:
              - key: cluster.ocs.openshift.io/openshift-storage
                operator: In
                values:
                - ""
        storageClassDevices:
          - storageClassName: localfile
            volumeMode: Filesystem  # Filesystem is for VMDK. Block for passthrough
            devicePaths: "{{ ocp_ocs.device_paths }}"

- name: Create an OCS Cluster Service using VMDK storage devices
  k8s:
    kubeconfig: "{{ ocp_ignition_file_path }}/auth/kubeconfig"
    state: present
    definition:
      kind: StorageCluster
      apiVersion: ocs.openshift.io/v1
      metadata:
        name: ocs-storagecluster
        namespace: openshift-storage
      spec:
        manageNodes: false
        monPVCTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1
            storageClassName: localfile
            volumeMode: Filesystem
```

Many thanks.

**Comment by Sispheor** [comment]
Once the LocalStorage created. Pods are ok
```
oc get pod,pvc -n openshift-local-storage
pod/local-file-local-diskmaker-525bc          1/1     Running   0          5m35s
pod/local-file-local-diskmaker-d6lc4          1/1     Running   0          5m35s
pod/local-file-local-diskmaker-mpct9          1/1     Running   0          5m35s
pod/local-file-local-provisioner-htjqr        1/1     Running   0          5m35s
pod/local-file-local-provisioner-jzsmw        1/1     Running   0          5m35s
pod/local-file-local-provisioner-zt7fs        1/1     Running   0          5m35s
pod/local-storage-operator-577f47fcff-qnffr   1/1     Running   0          6m45s

```

New PV created
```
oc get pv
NAME                CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS   REASON   AGE
local-pv-3933c701   100Gi      RWO            Delete           Available           localfile               5m53s
local-pv-96bd66f7   100Gi      RWO            Delete           Available           localfile               5m32s
local-pv-bd23b186   100Gi      RWO            Delete           Available           localfile               5m32s
```


But from the interface (I haven't executed the StorageCluster creation yet) if I try to create a StorageCluster from the UI. Nodes are not showing up  (note that the label `cluster.ocs.openshift.io/openshift-storage=""` is well applied)
![image](https://user-images.githubusercontent.com/2573405/101640273-9a823d80-3a30-11eb-86fa-a6c25d182b9a.png)

**Comment by Sispheor** [comment]
When creating manually, after a while a PVC for noobaa is created but stuck in pending state.

```
Generated from openshift-storage.rbd.csi.ceph.com_csi-rbdplugin-provisioner-75596f49bd-ms6v2_c5124d90-207a-418c-a51b-b260dcc8b9b2
5 times in the last 3 minutes
failed to provision volume with StorageClass "ocs-storagecluster-ceph-rbd": rpc error: code = InvalidArgument desc = failed to fetch monitor list using clusterID (openshift-storage): missing configuration for cluster ID (openshift-storage)
```

I missed something?

**Comment by Sispheor** [comment]
After a new deployment I get this error instead
```
failed to provision volume with StorageClass "ocs-storagecluster-ceph-rbd": rpc error: code = Internal desc = pool (ocs-storagecluster-cephblockpool) not found in Ceph cluster
```

**Comment by jarrpa** [comment]
Hello! Apologies for the delay.

I'm not a developer on the OCP console, so I can't reliably say why the nodes aren't showing up in the UI. I believe we are well supported on VMware, so the platform shouldn't be an issue... I might raise an issue with https://github.com/openshift/console/ and see if anyone responds there.

For the RBC errors, can you check to see if there is a CephBlockPool CR created in the openshift-storage namespace? If so please paste the YAML here. Either way, please also include the ocs-operator Pod logs, preferably as a gist or other external file, as that may contain some hints.

**Comment by Sispheor** [comment]
Hi, it's ok for the UI. I don't use it anyway.

About the storage. My local volume are ok. When I create them with this config:
```yaml
- name: Create local volume
  k8s:
    kubeconfig: "{{ ocp_ignition_file_path }}/auth/kubeconfig"
    state: present
    definition:
      apiVersion: local.storage.openshift.io/v1
      kind: LocalVolume
      metadata:
        name: local-file
        namespace: openshift-local-storage
        labels:
          app: ocs-storagecluster
      spec:
        nodeSelector:
          nodeSelectorTerms:
          - matchExpressions:
              - key: cluster.ocs.openshift.io/openshift-storage
                operator: In
                values:
                - ""
        storageClassDevices:
          - storageClassName: localfile
            volumeMode: Filesystem  
            devicePaths:
              - "/dev/disk/by-id/wwn-0x6000c29cda51eaa235d28a6429ddf52e" # ocs 0
              - "/dev/disk/by-id/wwn-0x6000c293df1e80a94a84c53bff69ff3d" # ocs 1
              - "/dev/disk/by-id/wwn-0x6000c296f88e57a2e2816f5c58db629c" # ocs 2
```

From my understanding "Filesystem" volumeMopde is for VMDK and  "Block" for passthrough. I hanv't found a doc that explain each yaml flags exactly.

After that I need to create the StorageCluster. But the storageDeviceSets expect a volumeMode "Block". So I cannot use my previously created localstorage that use Filesystem.
```yaml
- name: Create an OCS Cluster Service using VMDK storage devices
  k8s:
    kubeconfig: "{{ ocp_ignition_file_path }}/auth/kubeconfig"
    state: present
    definition:
      kind: StorageCluster
      apiVersion: ocs.openshift.io/v1
      metadata:
        name: ocs-storagecluster
        namespace: openshift-storage
      spec:
        manageNodes: false
        monPVCTemplate:
          spec:
            storageClassName: thin
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
        storageDeviceSets:
          - config: {}
            count: 1
            dataPVCTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1
                storageClassName: localfile
                volumeMode: Block
              status: {}
            name: ocs-deviceset
            placement: {}
            portable: true
            replica: 3
            resources: {}
```

If I go with this config, rook-ceph-osd-prepare-ocs-deviceset-0-data-0-ptjb8-q6lm5 pod is never created.
```
 1 node(s) didn't find available persistent volumes to bind,
```

deviceset PVC stay in pending status.
```
oc get pvc -n openshift-storage   
NAME                           STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                  AGE
ocs-deviceset-0-data-0-ptjb8   Pending                                                                        localfile                     43m
ocs-deviceset-1-data-0-d989l   Pending                                                                        localfile                     43m
ocs-deviceset-2-data-0-8qj6s   Pending                                                                        localfile                     43m
rook-ceph-mon-a                Bound     pvc-26effef6-b0db-4ee5-b734-ed29ea9c1bd2   10Gi       RWO            thin                          44m
rook-ceph-mon-b                Bound     pvc-11e8c914-b2b5-43f5-8dd2-0c413aacd851   10Gi       RWO            thin                          44m
rook-ceph-mon-c                Bound     pvc-ea98fc55-3838-4d67-827f-6e288a4783ed   10Gi       RWO            thin                          44m
```
